name: aura_eats
description: "AuraEats"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash/
    - assets/home/
    - assets/details/
    - assets/logo/

  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: font/LuckiestGuy-Regular.ttf
